# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
#   # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  # contentDir: content/i18n/en

# Uncomment the lines below to configure your website in a second language.
# zh:
#  languageCode: zh-Hans
# #  contentDir: content/i18n/zh

#  title: BioAI课题组
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
